{% set name = "cssselect" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cssselect-{{ version }}.tar.gz
  sha256: fdaf0a1425e17dfe8c5cf66191d211b357cf7872ae8afc4c6762ddd8ac47fc92

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.27.0

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - cssselect
  commands:
    - pip check

about:
  home: https://github.com/scrapy/cssselect
  license: BSD-3-Clause
  license_file: LICENSE
  summary: CSS Selectors for Python
  description: |
    Cssselect parses CSS3 Selectors and translate them to XPath 1.0
    expressions. Such expressions can be used in lxml or another XPath engine
    to find the matching elements in an XML or HTML document.
  doc_url: https://cssselect.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - vamega
    - thewchan
