{% set name = "cssselect" %}
{% set version = "1.3.0" %}
{% set sha256 = "e8792e44640e1852e02e7ae94ad261ca411fdbcf81150d18ad51afe8732164a4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scrapy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cssselect

about:
  home: https://pythonhosted.org/cssselect/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: CSS Selectors for Python
  description: |
    Cssselect parses CSS3 Selectors and translate them to XPath 1.0
    expressions. Such expressions can be used in lxml or another XPath engine
    to find the matching elements in an XML or HTML document.
  doc_url: https://cssselect.readthedocs.io/en/latest/
  doc_source_url: https://github.com/scrapy/cssselect/blob/master/README.rst
  dev_url: https://github.com/scrapy/cssselect

extra:
  recipe-maintainers:
    - vamega
