travis:
  secure:
    BINSTAR_TOKEN: J1guaLC0uyBzi3Zxn+3jFXLe8hpC2RLVQSwh5q6nXhGWyTl+4nT6ryoLcZdzm4lNv0t6cgbepuXRO3HU6jsV0/mpED6yFPA7HthU0XAVND+qETLDsFyEdpzxZGlwT7YHJZ5zpOozzDg6kBgRqIrLKOSUZvboBeozOODjscxgAjb/JhFRVuFwcFyXVzfYUayGOsG9xJquqZoh1jzuxz37Mq2N6Cc8wu9lxXcGdFv654pObD7LoPshHM/5HYiV+zeedUufTcLR+fXeXLcvsGsJaPxhwXVmQHME/7+cRVkBxFlEV8R+fgCg9O1qF3+lu4h8wYlzq+udVJxyWt2JQLpkVhYIbfmGTW/Lu5y7mdd713jRE5piOdI47UKTveG5gEHZzSOjf93yBOEeyKw4aNp6B9F7qCjfwo5TYkOW8QLZNAF7vzFk1TOqBTb9D6hNtIu21hO7IqAWAcaPQicBJNmrHEnkIZooqOtngtnQ4LXA/ND6y/o8ixEdFf48EbhZGb+xGmBvhvFc3No5mkak8t4Fx7KZqo7/Ssbmwtq/p3oI84YmBRMCEyJL2CnwuMks9+2uofKmPeW1xdjW0tughNpUXqtOE3TxqxSXIUXGAJz6YuBXpXzIcbfjtK+1mm4A3VtTU0e4IiUplxiovRBQkU2FX99AmoCKdLMBPturmvtYJT0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
